---
- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv dest=/home/{{ ansible_ssh_user }}/.rbenv

- name: install ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/{{ ansible_ssh_user }}/.rbenv/plugins/ruby-build

- name: install packages needed for compilation of/linking to Ruby
  apt: name={{item}} update_cache=yes state=present
  sudo: yes
  with_items:
    - autoconf
    - bison
    - build-essential
    - libffi-dev
    - libncurses5-dev
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
