#!/usr/bin/env bash

# Remove undesirable side effects of CDPATH variable
unset CDPATH
# Change current working directory to the directory contains this script
cd "$( dirname "${BASH_SOURCE[0]}" )"

# Initialize Bash Booster
source bashbooster.sh

apt-add-repository -y ppa:ansible/ansible
bb-apt-install ansible git
