- name: setup system defaults
  hosts: webservers
  roles:
    - system

- name: setup nginx
  hosts: webservers
  handlers:
  - include: handlers.yml
  roles:
    - nginx

- name: host www.vincecima.com static content via nginx
  hosts: www.vincecima.com
  handlers:
  - include: handlers.yml
  roles:
    - www.vincecima.com
