choco install crashplan
choco install iTunes
choco install mpc-hc
choco install path-copy-copy
choco install plex-home-theater
choco install plexmediaserver
choco install qbittorrent
choco install sharpkeys
choco install spotify
choco install steam
choco install unitywebplayer
choco install youtube-dl
choco install you-need-a-budget
