cinst crashplan
cinst iTunes
cinst plex-home-theater
cinst plexmediaserver
cinst qbittorrent
cinst sharpkeys
cinst spotify
cinst steam
cinst unitywebplayer
cinst virtualbox
cinst youtube-dl
cinst you-need-a-budget
