# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'trusty-tahir-cloud-image-latest'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.define :grace do |apps|
    apps.vm.network "private_network", ip: "192.168.10.12"
    apps.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh"
    apps.vm.network :forwarded_port, guest: 80, host: 8080, id: "http"
    apps.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
