---
- include_vars: destination.yml

- name: Remove destination from rsyslog
  sudo: yes
  lineinfile:
    dest: /etc/rsyslog.conf
    line: "*.* @{{ papertrail_destination_host }}:{{ papertrail_destination_port }}"
    state: absent
  notify:
    - restart rsyslog

- name: ensure service is stopped
  sudo: yes
  service:
    name: remote_syslog
    state: stopped
  ignore_errors: yes

- name: remove remote_syslog
  sudo: yes
  file:
    dest: /usr/local/bin/remote_syslog
    state: absent

- name: remove remote_syslog upstart conf
  sudo: yes
  file:
    dest: /etc/init/remote_syslog.conf
    state: absent

- name: remove remote_syslog conf
  sudo: yes
  file:
    dest: /etc/log_files.yml
    state: absent
